version: "3.8"

services:
  postgres_data:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: lamadev
      POSTGRES_PASSWORD: lama123456
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://lamadev:lama123456@147.79.87.101:5432/school
    depends_on:
      - postgres_data

volumes:
  postgres_data:
